name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - dask-labextension
  - distributed
  - dask-kubernetes
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - jupyter-server-proxy
  - jupyter
  - jupyterlab
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - nodejs
  - pip
  - pip:
    - git+https://github.com/intake/filesystem_spec@master
    - kubernetes
    - git+https://github.com/dask/gcsfs@master

